# -*- coding: utf-8 -*-
"""Course Recommendation based on required courses CS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2FSpZwwj0n4AYxi8BUFJ2HyLquxMK3i
"""

from google.colab import drive
drive.mount('/content/drive')

"""# ***Required Courses***"""

# Cell 1: Phase 1 Logic

import pandas as pd
import numpy as np
import re
from IPython.display import display

# =============================================================================
# Data Loading and Normalization
# =============================================================================
def load_course_data(file_path, sheet_name):
    """Loads and normalizes string columns."""
    try:
        df = pd.read_excel(file_path, engine='openpyxl', sheet_name=sheet_name)
        print(f"Loaded sheet '{sheet_name}' from {file_path}")
         # Apply basic normalization (lowercase strings)
        string_cols = df.select_dtypes(include=['object']).columns
        for col in string_cols:
             # Use .loc to potentially avoid SettingWithCopyWarning
             # Ensure conversion to string first for robustness
             df.loc[:, col] = df[col].apply(lambda x: str(x).strip().lower() if pd.notna(x) else x)
        # Ensure 'prerequisite(s)' column exists, fillna for safety
        if 'prerequisite(s)' not in df.columns:
             df['prerequisite(s)'] = '' # Add if missing, initialize with empty string
        df['prerequisite(s)'] = df['prerequisite(s)'].fillna('') # Fill NaN with empty string
        return df
    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
        return None
    except Exception as e:
        print(f"Error loading data from {file_path}, sheet {sheet_name}: {e}")
        return None

# =============================================================================
# Helper Functions (Define ALL needed helpers here)
# =============================================================================

def get_allowed_range(level_choice_num):
    """Maps academic level number (1-8) to min/max course number range."""
    ranges = {
        1: (100, 199), 2: (100, 199), 3: (200, 299), 4: (200, 299),
        5: (300, 399), 6: (300, 399), 7: (400, 499), 8: (400, 499)
    }
    return ranges.get(level_choice_num, (100, 499))

def extract_course_number(course_id):
    """Extracts the main number from a course ID string."""
    try:
        match = re.search(r'[a-z]{2,}\s*(\d{1,3})[a-z]?', str(course_id).lower())
        if match: return int(match.group(1))
        num_part = re.search(r'\d+', str(course_id))
        return int(num_part.group()) if num_part else 0
    except: return 0

def filter_courses_by_level(df, min_level, max_level, id_column='course number'):
    """Adds 'course_num_int' column and filters DataFrame by level range."""
    if id_column not in df.columns:
        print(f"Error: ID column '{id_column}' not found for level filtering.")
        return pd.DataFrame()
    df_copy = df.copy()
    # Use .loc to avoid SettingWithCopyWarning when adding column
    df_copy.loc[:, 'course_num_int'] = df_copy[id_column].apply(extract_course_number)
    filtered = df_copy[(df_copy['course_num_int'] >= min_level) & (df_copy['course_num_int'] <= max_level)]
    # Avoid inplace modification or chained indexing; return filtered DF without temp column
    return filtered.drop(columns=['course_num_int'], errors='ignore')


def check_prerequisites_v2(course, taken_courses_list, cs_df, level_choice, selected_courses_list=None, id_column='course number'):
    """ Checks if prerequisites for a course are met, handling 'and'/'or' logic using restricted eval. """
    # --- Full Implementation ---
    if selected_courses_list is None: selected_courses_list = []
    available_courses = set(str(c).strip().lower() for c in taken_courses_list + selected_courses_list if c is not None)
    course_lower = str(course).strip().lower()
    # Ensure cs_df id_column is comparable (string, lower)
    if id_column not in cs_df.columns: return True # Cannot check if column missing
    prereq_row = cs_df[cs_df[id_column].astype(str).str.strip().str.lower() == course_lower]
    if prereq_row.empty: return True # Assume no prereqs if not in CS list

    prereq_data = prereq_row['prerequisite(s)'].iloc[0]
    prereq_str = str(prereq_data) if pd.notna(prereq_data) else ''
    if not prereq_str or prereq_str.strip().lower() == 'none': return True

    original_prereq_str = prereq_str
    expression = original_prereq_str.strip().lower()
    course_codes = set(re.findall(r'([a-z]{2,}\s*\d{1,3}[a-z]?)', expression))

    if not course_codes and expression:
        print(f"Debug: Prereq for '{course}' ('{original_prereq_str}') non-standard text. Assuming unmet.")
        return False

    eval_context = {}
    all_prereqs_mentioned_individually_met = True

    for code in course_codes:
        is_met = False
        if course_lower == 'math 141' and level_choice == 2 and code == 'math 110': is_met = True
        elif code in available_courses: is_met = True
        else: all_prereqs_mentioned_individually_met = False
        safe_key = re.sub(r'[^a-zA-Z0-9_]', '_', code)
        if safe_key.isidentifier(): # Check if it's a valid Python identifier
             eval_context[safe_key] = is_met
        else:
             print(f"Warning: Generated invalid identifier '{safe_key}' from '{code}' for prereq eval.")
             # Cannot include this in eval context safely, may cause evaluation failure
             # Depending on logic (AND/OR), this might mean the requirement cannot be met
             pass # Or decide to return False immediately if any part is invalid

    eval_expression = expression
    eval_expression = re.sub(r'\band\b', ' and ', eval_expression)
    eval_expression = re.sub(r'\bor\b', ' or ', eval_expression)
    eval_expression = re.sub(r'\bnot\b', ' not ', eval_expression)
    eval_expression = eval_expression.replace(',', ' and ')
    eval_expression = eval_expression.replace('&', ' and ')
    eval_expression = eval_expression.replace('/', ' or ')

    sorted_course_codes = sorted(list(course_codes), key=len, reverse=True)
    for code in sorted_course_codes:
        safe_key = re.sub(r'[^a-zA-Z0-9_]', '_', code)
        if safe_key.isidentifier(): # Only substitute valid identifiers
            escaped_code = re.escape(code)
            eval_expression = re.sub(r'\b' + escaped_code + r'\b', safe_key, eval_expression)

    if eval_expression.count('(') != eval_expression.count(')'):
        print(f"Warning: Unbalanced parentheses in prereq for '{course}'. Assuming unmet.")
        return False
    eval_expression = ' '.join(eval_expression.split())

    try:
        eval_context['True'] = True; eval_context['False'] = False
        potential_leftovers = re.findall(r'[a-zA-Z_][a-zA-Z0-9_]+', eval_expression)
        valid_tokens = set(eval_context.keys()) | {'and', 'or', 'not', 'True', 'False'}
        unknown_tokens = [token for token in potential_leftovers if token not in valid_tokens]
        if unknown_tokens:
             print(f"Warning: Unknown tokens {unknown_tokens} in prereq expr for '{course}'. Assuming unmet.")
             return False

        result = eval(eval_expression, {"__builtins__": {}}, eval_context)
        # print(f"Debug: Evaluated prereq for '{course}': '{eval_expression}' -> {result}")
        return bool(result)
    except Exception as e:
        print(f"Error evaluating prereq '{eval_expression}' for {course}: {e}")
        has_logic_keywords = any(kw in expression for kw in [' and ', ' or ', '(', ')', ','])
        if not has_logic_keywords and len(course_codes) > 0:
            return all_prereqs_mentioned_individually_met
        else: return False
    # --- End Full Implementation ---

def get_required_courses():
    """Returns the list of core required CS courses (lowercase)."""
    # Ensure consistency with data (use lowercase)
    return [
        'bio 244', 'cmsc 141', 'cmsc 143', 'cmsc 145', 'cmsc 201',
        'cmsc 225', 'cmsc 226', 'cmsc 275', 'cmsc 301', 'cmsc 305',
        'cmsc 325', 'cmsc 326', 'cmsc 328', 'cmsc 335', 'econ 229',
        'math 141', 'psy 203', #'senior project' # Map senior project if needed
    ]

def get_remaining_requirements(taken_courses_list):
    """Calculates remaining requirement categories."""
    # Ensure categories match course IDs or groups used elsewhere
    req_map = {
        'math 141': ['math 141'],
        'cmsc 141 / cmsc 143': ['cmsc 141', 'cmsc 143'],
        'cmsc 145': ['cmsc 145'],
        'cmsc 201': ['cmsc 201'],
        'statistics': ['cmsc 275', 'bio 244', 'psy 203', 'econ 229'],
        'cmsc 301': ['cmsc 301'],
        'cmsc 305': ['cmsc 305'],
        'systems': ['cmsc 225', 'cmsc 226', 'cmsc 325', 'cmsc 326', 'cmsc 328', 'cmsc 335'],
        #'senior project': ['senior project'], # Map to actual course ID(s)
        'electives': []
    }
    taken_set = set(c.lower() for c in taken_courses_list) # Ensure lowercase comparison
    remaining = []

    for category, courses in req_map.items():
        if category == 'electives':
            remaining.append(category)
            continue
        if not courses: continue
        # Check if ANY course fulfilling the category requirement has been taken
        is_met = any(course.lower() in taken_set for course in courses)
        if not is_met:
            remaining.append(category)

    return sorted(list(set(remaining))) # Return unique sorted list


def list_available_courses_for_requirement(cs_df, general_df, requirement_category, taken_courses, min_level, max_level, semester, level_choice, selected_courses=None):
    """ Filters and lists available courses for a specific requirement category for Phase 1. """
    # --- Full Implementation ---
    if selected_courses is None: selected_courses = []
    if cs_df is None or general_df is None: return pd.DataFrame()

    cs_id_column = 'course number'; general_id_column = 'course number'
    cs_title_column = 'course title'; general_title_column = 'course title'
    semester_norm = semester.lower() # Ensure semester is lowercase for comparison

    # Assume 'semester' in general_df is already normalized by load_course_data
    offered_df = general_df[general_df['semester'] == semester_norm]
    if offered_df.empty: return pd.DataFrame()

    candidate_courses_df = pd.DataFrame()
    requirement_lower = requirement_category.lower()
    # Use same req_map as get_remaining_requirements for consistency
    req_map = {
        'math 141': ['math 141'], 'cmsc 141 / cmsc 143': ['cmsc 141', 'cmsc 143'],
        'cmsc 145': ['cmsc 145'], 'cmsc 201': ['cmsc 201'],
        'statistics': ['cmsc 275', 'bio 244', 'psy 203', 'econ 229'],
        'cmsc 301': ['cmsc 301'], 'cmsc 305': ['cmsc 305'],
        'systems': ['cmsc 225', 'cmsc 226', 'cmsc 325', 'cmsc 326', 'cmsc 328', 'cmsc 335'],
        #'senior project': ['senior project'], # Map if needed
    }

    if requirement_lower == 'electives':
        candidate_courses_df = cs_df[cs_df[cs_id_column].str.startswith('cmsc', na=False)].copy()
        # Use student's level range for electives unless specified otherwise
        candidate_courses_df = filter_courses_by_level(candidate_courses_df, min_level, max_level, cs_id_column)
    elif requirement_lower in req_map:
        target_ids = req_map[requirement_lower]
        if not target_ids: return pd.DataFrame()
        candidate_courses_df = cs_df[cs_df[cs_id_column].isin(target_ids)].copy()
    else: # Assume it's a specific course ID (already lowercased from req list)
        candidate_courses_df = cs_df[cs_df[cs_id_column] == requirement_lower].copy()

    if candidate_courses_df.empty: return pd.DataFrame()

    # Ensure IDs are lowercase for matching
    offered_in_semester_ids = set(offered_df[general_id_column].unique()) # Set for faster lookup
    candidate_courses_df = candidate_courses_df[candidate_courses_df[cs_id_column].isin(offered_in_semester_ids)]
    if candidate_courses_df.empty: return pd.DataFrame()

    filtered_cs_level = filter_courses_by_level(candidate_courses_df, min_level, max_level, cs_id_column)
    if filtered_cs_level.empty: return pd.DataFrame()

    # Apply prerequisite check
    available_mask = filtered_cs_level[cs_id_column].apply(
        lambda course_id: check_prerequisites_v2(
            course=course_id, taken_courses_list=taken_courses, cs_df=cs_df,
            level_choice=level_choice, selected_courses_list=selected_courses, id_column=cs_id_column
        )
    )
    final_available_df = filtered_cs_level[available_mask] # No need for .copy() if just filtering
    if final_available_df.empty: return pd.DataFrame()

    # Prepare display columns
    display_columns = [cs_id_column, cs_title_column]
    if 'credits' in final_available_df.columns: display_columns.append('credits')
    existing_display_columns = [col for col in display_columns if col in final_available_df.columns]

    return final_available_df[existing_display_columns].drop_duplicates().reset_index(drop=True)
    # --- End Full Implementation ---


def get_next_semester(current_semester_str):
    """Calculates the next semester string."""
    parts = str(current_semester_str).lower().strip().split()
    if len(parts) != 2: return None
    season, year_str = parts
    try:
        year = int(year_str)
        if season == 'spring': return f"fall {year}"
        elif season == 'fall': return f"spring {year + 1}"
        else: return None
    except ValueError: return None

def parse_prereqs_to_list(prereq_str):
    """Extracts potential course codes mentioned in a prerequisite string."""
    if pd.isna(prereq_str) or not prereq_str: return []
    # Find patterns like 'word(s)[space]number[optional letter]' (case-insensitive)
    course_codes = re.findall(r'([a-z]{2,}\s*\d{1,3}[a-z]?)', str(prereq_str).lower())
    return sorted(list(set(course_codes)))


# =============================================================================
# Phase 1 Main Function (Returns results for Phase 2)
# =============================================================================
def main_phase1():
    """Runs Phase 1: Gets inputs, recommends for Semester T, returns results."""
    cs_file_path = "/content/drive/MyDrive/Shared Folder/Course_Recommendation_System/Data/Processed/CS Course list.xlsx"
    general_file_path = "/content/drive/MyDrive/Shared Folder/Course_Recommendation_System/Data/Processed/draft_course_fall21_spring2025.xlsx"

    print("Loading course data for Phase 1...")
    # Use the load_course_data function which normalizes and handles NaNs
    cs_courses_df = load_course_data(cs_file_path, 'CS Courses')
    general_courses_df = load_course_data(general_file_path, 'courses')

    if cs_courses_df is None or general_courses_df is None:
        print("Error: Essential course data could not be loaded. Exiting Phase 1.")
        return None

    required_cols_check = ['semester', 'course number', 'course title', 'prerequisite(s)']
    if not all(col in cs_courses_df.columns for col in ['course number', 'course title', 'prerequisite(s)']):
         print(f"Error: CS Courses DF missing required columns."); return None
    if not all(col in general_courses_df.columns for col in ['semester', 'course number']):
         print(f"Error: General Courses DF missing required columns."); return None

    # Ensure 'semester' column exists and get unique semesters (already lowercased)
    unique_semesters = sorted(general_courses_df['semester'].dropna().unique())
    if not unique_semesters: print("Error: No semesters found in data."); return None

    # --- Get User Inputs ---
    print("\n--- Course Planning: Phase 1 ---")
    print("\nPlease choose the semester you are planning for:")
    for i, sem in enumerate(unique_semesters, 1): print(f"{i}. {sem}")
    try:
        sem_choice_num = int(input("Enter the number of the target semester: "))
        if 1 <= sem_choice_num <= len(unique_semesters): chosen_semester = unique_semesters[sem_choice_num - 1]
        else: print("Invalid semester choice."); return None
    except ValueError: print("Invalid input."); return None
    print(f"Planning for semester: {chosen_semester}")

    levels = ['Freshman I', 'Freshman II', 'Sophomore I', 'Sophomore II', 'Junior I', 'Junior II', 'Senior I', 'Senior II']
    print("\nPlease choose your academic level for that semester:")
    for i, lvl in enumerate(levels, 1): print(f"{i}. {lvl}")
    try:
        level_choice = int(input("Enter the number of your academic level: "))
        if not (1 <= level_choice <= len(levels)): print("Invalid level choice."); return None
        level_name = levels[level_choice-1]
        print(f"Level chosen: {level_name}")
    except ValueError: print("Invalid input."); return None
    min_level_T, max_level_T = get_allowed_range(level_choice)

    all_required_courses = get_required_courses()
    print("\nList of required Computer Science Program courses:")
    for idx, course in enumerate(all_required_courses, 1): print(f"{idx}. {course}") # Show original case
    taken_courses_input = input(f"\nEnter numbers of REQUIRED courses ALREADY TAKEN (before {chosen_semester}), separated by commas: ")
    taken_courses = []
    try:
        taken_indices = [int(i.strip()) for i in taken_courses_input.split(',') if i.strip()]
        # Store as lowercase list
        taken_courses = [all_required_courses[i-1].lower() for i in taken_indices if 1 <= i <= len(all_required_courses)]
    except (ValueError, IndexError): print("Invalid input for taken courses. Assuming none.")
    print("\nCourses taken before chosen semester:", taken_courses if taken_courses else "None")

    # --- Generate and Select Recommendations ---
    remaining_requirements = get_remaining_requirements(taken_courses)
    print("\nRemaining program requirements to fulfill:", remaining_requirements)
    selected_courses = [] # Renamed from selected_courses_T for clarity in return
    recommendations_T = {}
    print(f"\n--- Course Options for {chosen_semester} (Level: {level_name}) ---")

    for req_category in remaining_requirements:
        if req_category == 'electives': print(f"\nSkipping automatic recommendation for '{req_category}'. Please check catalog."); continue

        print(f"\nAvailable courses for requirement '{req_category}':")
        available_df = list_available_courses_for_requirement(
            cs_courses_df, general_courses_df, req_category, taken_courses,
            min_level_T, max_level_T, chosen_semester, level_choice, selected_courses # Pass current selections
        )

        if available_df.empty: print("  No suitable courses found.")
        else:
            if 'course number' not in available_df.columns or 'course title' not in available_df.columns:
                 print("  Error: list_available_courses_for_requirement did not return required columns."); continue

            available_list = available_df[['course number', 'course title']].to_dict('records')
            for idx, course_info in enumerate(available_list):
                c_num = course_info.get('course number', 'N/A') # Already lowercase
                c_title = course_info.get('course title', 'N/A') # Already lowercase
                print(f"  {idx+1}. {c_num} {c_title}")

            try:
                choice = int(input(f"  Enter number for '{req_category}' (or 0 to skip): "))
                if 1 <= choice <= len(available_list):
                    selected_course_id = available_list[choice - 1].get('course number')
                    if selected_course_id and selected_course_id != 'N/A':
                        if selected_course_id not in selected_courses:
                             selected_courses.append(selected_course_id) # Add lowercase ID
                             recommendations_T[req_category] = selected_course_id
                             print(f"  Selected: {selected_course_id}")
                        else: print(f"  '{selected_course_id}' already selected.")
                elif choice != 0: print("  Invalid choice. Skipping.")
            except ValueError: print("  Invalid input. Skipping.")

    # --- Phase 1 Summary ---
    print("\n---------------------------------------------------------")
    print(f"--- Summary of Your Selections for {chosen_semester} ---")
    if not selected_courses: print("No courses selected for this semester.")
    else:
        print("Selected Courses:")
        if 'course number' in cs_courses_df.columns and 'course title' in cs_courses_df.columns:
             for course_id in selected_courses: # course_id is lowercase
                  title_row = cs_courses_df[cs_courses_df['course number'] == course_id]
                  title = title_row['course title'].iloc[0] if not title_row.empty else '(Title not found)'
                  print(f"- {course_id} {title}") # Display lowercase id and title
        else: print("- " + "\n- ".join(selected_courses))
    print("---------------------------------------------------------")

    # Return results needed for Phase 2
    return {
        'chosen_semester': chosen_semester,
        'level_choice': level_choice,
        'taken_courses': taken_courses, # List of lowercase strings
        'selected_courses': selected_courses, # List of lowercase strings
        'cs_courses_df': cs_courses_df,
        'general_courses_df': general_courses_df,
        'levels_list': levels
    }

# =============================================================================
# Run Phase 1 (To be placed in the first Colab cell)
# =============================================================================
if __name__ == "__main__":
    # Optional: Mount drive if needed in Colab
    # from google.colab import drive
    # drive.mount('/content/drive')

    print("Starting Phase 1...")
    phase1_results = main_phase1()

    if phase1_results:
        print("\nPhase 1 completed. Results stored in 'phase1_results'.")
        # Make DataFrames accessible globally for Cell 2
        cs_courses_df = phase1_results['cs_courses_df']
        general_courses_df = phase1_results['general_courses_df']
        print("DataFrames 'cs_courses_df' and 'general_courses_df' are available.")
    else:
        print("\nPhase 1 failed or exited.")

# Cell 2: Phase 2 Logic
# Assuming Cell 1 run successfully and 'phase1_results',
# 'cs_courses_df', and 'general_courses_df' variables exist.

import pandas as pd
import numpy as np
import re
from IPython.display import display # If using Colab/Jupyter

print("\n=========================================================================")
print(f"--- Prerequisite Planning: Phase 2 ---")
print("=========================================================================")

# Check if Phase 1 results are available
if 'phase1_results' not in locals() or not phase1_results:
    print("Error: Phase 1 results not found. Please run the Phase 1 cell first.")
# Check if DataFrames are available (assuming Cell 1 made them global)
elif 'cs_courses_df' not in locals() or 'general_courses_df' not in locals():
     print("Error: Required DataFrames (cs_courses_df, general_courses_df) not found. Ensure Phase 1 cell ran correctly.")
else:
    # Extract data from Phase 1 results
    chosen_semester = phase1_results['chosen_semester']     # lowercase string
    level_choice = phase1_results['level_choice']           # int (1-8)
    taken_courses = phase1_results['taken_courses']         # list of lowercase strings
    selected_courses_T = phase1_results['selected_courses'] # list of lowercase strings (renamed for clarity)
    levels = phase1_results['levels_list']                  # list of level names

    # --- Start Phase 2 Logic ---
    next_semester_str = get_next_semester(chosen_semester)
    if not next_semester_str:
        print(f"Could not determine the semester following {chosen_semester}. Skipping Phase 2.")
    else:
        print(f"Checking prerequisites needed for potential required courses in {next_semester_str}...")

        next_level_choice = min(level_choice + 1, 8)
        min_next_level, max_next_level = get_allowed_range(next_level_choice)
        print(f"(Targeting required courses for level {levels[next_level_choice-1]}, range {min_next_level}-{max_next_level})")

        courses_met_up_to_T_set = set(taken_courses + selected_courses_T) # lowercase set

        required_cs_courses = get_required_courses() # lowercase list
        target_t_plus_1_courses = [] # list of lowercase strings
        for req_course in required_cs_courses:
            if req_course in courses_met_up_to_T_set: continue
            num = 0
            if req_course == 'senior project': num = 490 # Placeholder level for senior project
            else: num = extract_course_number(req_course) # Expects lowercase

            if not (min_next_level <= num <= max_next_level): continue
            target_t_plus_1_courses.append(req_course)

        print(f"Potential unmet required courses targeted for {next_semester_str}: {target_t_plus_1_courses}")

        missing_prereqs_map = {} # maps lowercase missing prereq -> list of lowercase target courses
        for target_course in target_t_plus_1_courses: # lowercase target
            is_target_met = check_prerequisites_v2(
                target_course, taken_courses, cs_courses_df, next_level_choice, selected_courses_T
            )
            if not is_target_met:
                prereq_row = cs_courses_df[cs_courses_df['course number'] == target_course]
                if not prereq_row.empty:
                    prereq_data = prereq_row['prerequisite(s)'].iloc[0] # Already lowercase string
                    prereq_str = str(prereq_data) if pd.notna(prereq_data) else ''
                    if prereq_str and prereq_str != 'none':
                        mentioned_prereqs = parse_prereqs_to_list(prereq_str) # lowercase list
                        for prereq in mentioned_prereqs:
                            if prereq not in courses_met_up_to_T_set:
                                if prereq not in missing_prereqs_map: missing_prereqs_map[prereq] = []
                                if target_course not in missing_prereqs_map[prereq]:
                                    missing_prereqs_map[prereq].append(target_course)


        missing_prereqs_for_T = set(missing_prereqs_map.keys()) # Set of lowercase prereq IDs
        if not missing_prereqs_for_T:
            print(f"All identified prerequisites for potential {next_semester_str} required courses seem met by the end of {chosen_semester}.")
        else:
            print(f"Identified missing prerequisites needed for {next_semester_str}: {missing_prereqs_for_T}")
            phase2_recommendations = []
            min_level_T, max_level_T = get_allowed_range(level_choice) # Range for current semester T

            if not {'semester', 'course number'}.issubset(general_courses_df.columns):
                 print("Error: Missing columns in general offerings data.")
            else:
                 # Ensure comparison uses lowercase semester; course numbers are already lowercase
                 offered_in_T = set(general_courses_df[general_courses_df['semester'] == chosen_semester]['course number'].unique())

                 for prereq in missing_prereqs_for_T: # lowercase prereq
                    if prereq not in offered_in_T: continue
                    prereq_num = extract_course_number(prereq)
                    if not (min_level_T <= prereq_num <= max_level_T): continue
                    # Check prereqs for the prereq using only courses taken BEFORE T
                    if not check_prerequisites_v2(prereq, taken_courses, cs_courses_df, level_choice, None):
                         print(f"  (Note: Cannot recommend '{prereq}'; its own prereqs not met before {chosen_semester})")
                         continue
                    needed_for_list = missing_prereqs_map.get(prereq, [])
                    phase2_recommendations.append({'course': prereq, 'needed_for': ", ".join(needed_for_list)})

            print(f"\n--- Additional Recommendations for {chosen_semester} (to prepare for {next_semester_str}) ---")
            if not phase2_recommendations:
                print("No specific prerequisite courses recommended this semester.")
            else:
                print(f"Consider taking these in {chosen_semester} to fulfill prerequisites for future required courses:")
                phase2_recommendations.sort(key=lambda x: x['course'])
                for item in phase2_recommendations:
                     title_row = cs_courses_df[cs_courses_df['course number'] == item['course']]
                     title = title_row['course title'].iloc[0] if not title_row.empty else '(Title not found)'
                     needed_for_str = item['needed_for']
                     if len(needed_for_str) > 60: needed_for_str = needed_for_str[:57] + "..."
                     print(f"- {item['course']} {title} (Helps satisfy prerequisite for: {needed_for_str})")

        print(f"--- End of Prerequisite Planning ---")
        print("=========================================================================")

# End of Cell 2

"""# ***Distribution Requirement***"""

"""
Topic Search using TF-IDF (Standalone Script for Colab)
"""

import pandas as pd
import numpy as np
import re
import string # For punctuation removal
from IPython.display import display # For better DataFrame printing in Colab

# --- Imports for TF-IDF and Text Processing ---
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.corpus import stopwords

# =============================================================================
# Download NLTK Stopwords if necessary
# =============================================================================
try:
    # Try to load stopwords directly
    stop_words = stopwords.words('english')
    print("NLTK stopwords found.")
except LookupError: # Corrected Exception Type
    print("NLTK stopwords not found. Downloading...")
    try:
        nltk.download('stopwords', quiet=True)
        # Try loading again after download
        stop_words = stopwords.words('english')
        print("NLTK stopwords downloaded successfully.")
    except Exception as e:
        # Handle potential download/network errors
        print(f"Error downloading NLTK stopwords: {e}")
        print("Proceeding without stopwords. Search results may be less accurate.")
        stop_words = [] # Use empty list as fallback

# Ensure stop_words exists (as a fallback if all else failed)
if 'stop_words' not in locals():
    stop_words = []

# =============================================================================
# Helper Functions (Keep all defined here)
# =============================================================================
def get_choice_from_list(options_list, prompt_message):
    """Displays options, gets numbered choice, returns (choice_str, choice_num)."""
    print(f"\n{prompt_message}")
    if not options_list: print("No options available."); return None, None
    for i, option in enumerate(options_list, 1): print(f"{i}. {option}")
    while True:
        try:
            choice_num = int(input("Enter the number of your choice: "))
            if 1 <= choice_num <= len(options_list): return options_list[choice_num - 1], choice_num
            else: print(f"Invalid number. Please enter 1-{len(options_list)}.")
        except ValueError: print("Invalid input. Please enter a number.")

def get_allowed_range(level_choice_num):
    """Maps academic level number (1-8) to min/max course number range."""
    ranges = {
        1: (100, 199), 2: (100, 199), 3: (200, 299), 4: (200, 299),
        5: (300, 399), 6: (300, 399), 7: (400, 499), 8: (400, 499)
    }
    return ranges.get(level_choice_num, (100, 499))

def extract_course_number(course_id):
    """Extracts the main number from a course ID string."""
    try:
        num_part = re.search(r'\d+', str(course_id))
        return int(num_part.group()) if num_part else 0
    except: return 0

def parse_distribution_str(distribution_str):
    """Parses comma/space/plus separated distribution codes."""
    if pd.isna(distribution_str) or not distribution_str: return []
    codes = re.split(r'[,\s\+]+', str(distribution_str))
    return [code.strip().upper() for code in codes if code.strip()]

def preprocess_text(text):
    """Cleans text for TF-IDF."""
    if pd.isna(text): return ""
    text = str(text).lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

def perform_topic_search_tfidf(filtered_df_input):
    """ Performs TF-IDF search *on the provided pre-filtered DataFrame*. """
    print("\n--- Searching by Topic within filtered results ---")
    if filtered_df_input.empty:
        print("Cannot perform topic search as no courses match the initial Level/Semester criteria.")
        return

    # Work on a copy
    courses_df = filtered_df_input.copy()

    text_columns = ['course title', 'course description', 'course description.1']
    valid_text_columns = [col for col in text_columns if col in courses_df.columns]
    if not valid_text_columns:
        print(f"Error: Could not find required text columns {text_columns} for topic search.")
        return
    print(f"Searching within columns: {valid_text_columns}")

    # Combine text, handle NaNs (might already be done, but safe to repeat)
    courses_df['text_for_search'] = courses_df[valid_text_columns].fillna('').astype(str).agg(' '.join, axis=1)
    print("Preprocessing course text...")
    courses_df['preprocessed_text'] = courses_df['text_for_search'].apply(preprocess_text)

    print("Building TF-IDF model (on filtered data)...")
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(courses_df['preprocessed_text']) # Fit only on filtered data

    query = input("Enter your topic query (e.g., 'introduction to machine learning'): ").strip()
    if not query: print("No query entered."); return
    preprocessed_query = preprocess_text(query)
    if not preprocessed_query: print("Query invalid after preprocessing."); return

    query_vector = vectorizer.transform([preprocessed_query]) # Transform using the fitted vectorizer
    print("Calculating similarity...")
    cosine_similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()

    N = 10
    similarity_threshold = 0.05 # Adjust as needed
    top_n_indices_local = np.argsort(cosine_similarities)[-N:][::-1] # Indices relative to the filtered_df

    # Filter local indices by threshold
    relevant_indices_local = [i for i in top_n_indices_local if cosine_similarities[i] > similarity_threshold]

    if not relevant_indices_local:
        print(f"\nNo relevant courses found within the filtered set for query: '{query}'")
        return

    print(f"\nTop {len(relevant_indices_local)} relevant courses found for query: '{query}'")

    # Retrieve results using the local indices on the input DataFrame
    results_df = courses_df.iloc[relevant_indices_local].copy()
    results_df['similarity_score'] = cosine_similarities[relevant_indices_local]

    display_cols = ['course number', 'course title', 'semester', 'program', 'similarity_score', 'course description']
    display_cols = [col for col in display_cols if col in results_df.columns]
    results_df = results_df.sort_values(by='similarity_score', ascending=False)
    display(results_df[display_cols])

# =============================================================================
# Main Program Execution (Refactored Flow)
# =============================================================================

# --- Define File Path ---
dataset_file_path = "/content/drive/MyDrive/Shared Folder/Course_Recommendation_System/Data/Processed/draft_course_fall21_spring2025.xlsx"

# --- Load Data ---
print(f"Loading data from: {dataset_file_path}")
try:
    main_courses_df = pd.read_excel(dataset_file_path)
    print(f"Successfully loaded {len(main_courses_df)} courses.")
except FileNotFoundError:
    print(f"Error: File not found at {dataset_file_path}"); exit(1)
except Exception as e:
    print(f"Error reading the dataset: {e}"); exit(1)

# --- Initial User Input: Level and Semester ---
if 'main_courses_df' in locals() and not main_courses_df.empty:
    # Step 1: Get Academic Level
    levels = ['Freshman I', 'Freshman II', 'Sophomore I', 'Sophomore II', 'Junior I', 'Junior II', 'Senior I', 'Senior II']
    level_name_choice, level_num_choice = get_choice_from_list(levels, "Please choose your academic level:")
    if level_name_choice is None: exit(1)
    min_level, max_level = get_allowed_range(level_num_choice)
    print(f"\nLevel chosen: {level_name_choice} (Range: {min_level}-{max_level})")

    # Step 2: Get Semester
    required_columns_initial = ["semester", "course number"] # Check needed columns early
    if not all(col in main_courses_df.columns for col in required_columns_initial):
        print(f"Error: Dataset missing one/more required columns: {required_columns_initial}"); exit(1)

    main_courses_df["semester_norm"] = main_courses_df["semester"].astype(str).str.strip().str.lower()
    unique_semesters = sorted(main_courses_df["semester_norm"].dropna().unique())
    semester_choice, _ = get_choice_from_list(unique_semesters, "Please choose a semester:")
    if semester_choice is None: exit(1)
    print(f"Semester chosen: {semester_choice}")

    # --- Apply Initial Filters (Semester and Level) ---
    print("\nApplying initial Semester and Level filters...")
    # Filter by Semester
    semester_filtered_df = main_courses_df[main_courses_df["semester_norm"] == semester_choice].copy()
    if semester_filtered_df.empty:
        print(f"No courses found offered in {semester_choice}.")
        exit(0)

    # Filter by Level
    id_column = 'course number'
    semester_filtered_df.loc[:, 'course_num_int'] = semester_filtered_df[id_column].apply(extract_course_number)
    semester_level_filtered_df = semester_filtered_df[
        (semester_filtered_df['course_num_int'] >= min_level) &
        (semester_filtered_df['course_num_int'] <= max_level)
    ].copy()

    if semester_level_filtered_df.empty:
        print(f"No courses found in {semester_choice} matching the level range {min_level}-{max_level}.")
        exit(0)

    print(f"Found {len(semester_level_filtered_df)} courses matching semester '{semester_choice}' and level '{level_name_choice}'.")

    # --- Ask User for Search/Filter Method ---
    search_methods = [
        f"Further filter these {len(semester_level_filtered_df)} courses by Program / Distribution Area",
        f"Search by Topic within these {len(semester_level_filtered_df)} courses"
    ]
    search_choice_name, search_choice_num = get_choice_from_list(search_methods, "How would you like to proceed?")

    # --- Execute chosen method on the pre-filtered data ---
    if search_choice_num == 1:
        # --- Further Filtering Logic ---
        print("\n--- Further Filtering Courses ---")
        filtered_courses = semester_level_filtered_df.copy() # Start with pre-filtered data

        required_columns_filter = ["program", "dist area"]
        if not all(col in filtered_courses.columns for col in required_columns_filter):
             print(f"Error: Dataset missing one/more required columns for filtering: {required_columns_filter}"); exit(1)

        # Filter by Program
        filtered_courses["program_norm"] = filtered_courses["program"].astype(str).str.strip().str.lower()
        relevant_programs = sorted(filtered_courses["program_norm"].dropna().unique())
        if not relevant_programs:
             print("No programs found in the filtered course list.")
             # Display current results if no further filtering possible
             display_cols = [col for col in main_courses_df.columns if '_norm' not in col and col != 'course_num_int']
             display_cols = [col for col in display_cols if col in filtered_courses.columns]
             display(filtered_courses[display_cols].head())
             exit(0)

        program_choice, _ = get_choice_from_list(relevant_programs, f"Please choose a program offered:")
        if program_choice is None: exit(1)
        filtered_courses = filtered_courses[filtered_courses["program_norm"] == program_choice].copy()
        if filtered_courses.empty: print(f"\nNo courses found for program '{program_choice}'."); exit(0)
        print(f"\nFound {len(filtered_courses)} courses for program '{program_choice}'.")

        # Filter by Distribution Area
        relevant_dist_codes_set = set()
        for area_str in filtered_courses["dist area"].dropna(): relevant_dist_codes_set.update(parse_distribution_str(area_str))
        relevant_dist_codes_set.discard(''); relevant_dist_codes_set.discard('NONE')
        relevant_sorted_dist_codes = sorted(list(relevant_dist_codes_set))

        dist_area_choice = "N/A"
        if relevant_sorted_dist_codes:
            dist_area_choice, _ = get_choice_from_list(relevant_sorted_dist_codes, f"Please choose a distribution area offered:")
            if dist_area_choice is None: exit(1)
            filtered_courses = filtered_courses[filtered_courses["dist area"].apply(lambda x: dist_area_choice in parse_distribution_str(x))].copy()
            if filtered_courses.empty: print(f"\nNo courses found matching distribution area '{dist_area_choice}'."); exit(0)
            print(f"\nFound {len(filtered_courses)} courses matching distribution area '{dist_area_choice}'.")
        else:
            print(f"\nNo specific distribution areas found to filter by.")

        # Final Output for Filtering Path
        print(f"\nFinal {len(filtered_courses)} courses matching all criteria:\n")
        display_cols = [col for col in main_courses_df.columns if '_norm' not in col and col != 'course_num_int']
        display_cols = [col for col in display_cols if col in filtered_courses.columns]
        display(filtered_courses[display_cols].head())


    elif search_choice_num == 2:
        # --- Topic Search Logic ---
        # Call the TF-IDF search function, passing the semester-level filtered DataFrame
        perform_topic_search_tfidf(semester_level_filtered_df)

    else:
        print("Invalid method selected.")

else:
     print("DataFrame was not loaded successfully. Cannot proceed.")

# End of script